version: '3'

services:
  rabbitmq:
    image: rabbitmq:alpine
    hostname: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ messaging port
      - "15672:15672"  # RabbitMQ management plugin port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persist RabbitMQ data
    networks:
      - rabbitmq_network
volumes:
  rabbitmq_data:

networks:
  rabbitmq_network:
    driver: bridge
